### ISSUE TITLE
ValidationError when building the app

### ISSUE THREAD

**Issue by MarAlder** [megasanjay/electron-vue3-flask#15]
I'm trying to understand how to combine vuejs, flask and electron and your project is a great support, thank you for this!!

Everything works out fine (with `yarn electron:serve`) until I try the local build. Maybe you can help me understanding and resolving my error message.

**Describe the bug**
```yarn electron:build``` 
returns
```ValidationError: Invalid configuration object. electron-builder 22.14.13 has been initialized using a configuration object that does not match the API schema.```

**To Reproduce**
1. Clone project to Win64 OS
2. ```yarn install``` (runs through successfully)
3. Run ```python -m PyInstaller --onefile --clean ./src/pyflask/api.py --distpath ./src/pyflaskdist``` from my conda environment (app.exe successfully generated)
4. ```yarn electron:build```
5. See error

**Expected behavior**
I would expect the application to be build.

**Screenshots**
```
>> yarn electron:build
yarn run v1.22.19
$ vue-cli-service electron:build
 INFO  Bundling render process:

-  Building modern bundle for production...

 DONE  Compiled successfully in 23104ms                                                                                                                                                                  07:04:54
  File                                                  Size                                                                       Gzipped

  dist_electron\bundled\js\chunk-vendors.f7fbcfb3.js    116.25 KiB                                                                 40.96 KiB
  dist_electron\bundled\js\app.c256f487.js              4.27 KiB                                                                   1.92 KiB
  dist_electron\bundled\css\app.2777c4eb.css            5.23 KiB                                                                   1.71 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist_electron\bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

\  Bundling main process...

 DONE  Compiled successfully in 1117ms                                                                                                                                                                   07:04:55
  File                                   Size                                                                               Gzipped

  dist_electron\bundled\background.js    397.07 KiB                                                                         124.26 KiB

  Images and other types of assets omitted.

-  Bundling preload files...

 DONE  Compiled successfully in 103ms                                                                                                                                                                    07:04:55
  File                                Size                                                                                Gzipped

  dist_electron\bundled\preload.js    1.28 KiB                                                                            0.60 KiB

  Images and other types of assets omitted.

 INFO  Building app with electron-builder:
  • electron-builder  version=22.14.13 os=10.0.19044
ValidationError: Invalid configuration object. electron-builder 22.14.13 has been initialized using a configuration object that does not match the API schema.
 - configuration.publish should be one of these:
   object { provider, channel?, host?, owner?, private?, protocol?, publishAutoUpdate?, publisherName?, releaseType?, repo?, requestHeaders?, token?, updaterCacheDirName?, vPrefixedTagName? } | object { bucket, provider, acl?, channel?, encryption?, endpoint?, path?, publishAutoUpdate?, publisherName?, region?, requestHeaders?, storageClass?, updaterCacheDirName? } | object { name, provider, region, acl?, channel?, path?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, url, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName?, useMultipleRangeRequest? } | object { provider, component?, distribution?, owner?, package?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, token?, updaterCacheDirName?, user? } | object { provider, publishAutoUpdate?, publisherName?, requestHeaders?, updateProvider?, updaterCacheDirName?, <key>: {} } | object { account, product, provider, channel?, platform?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, channels?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, updaterCacheDirName? } | object { owner, provider, slug, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, token?, updaterCacheDirName?, username? } | [object { provider, channel?, host?, owner?, private?, protocol?, publishAutoUpdate?, publisherName?, releaseType?, repo?, requestHeaders?, token?, updaterCacheDirName?, vPrefixedTagName? } | object { bucket, provider, acl?, channel?, encryption?, endpoint?, path?, publishAutoUpdate?, publisherName?, region?, requestHeaders?, storageClass?, updaterCacheDirName? } | object { name, provider, region, acl?, channel?, path?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, url, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName?, useMultipleRangeRequest? } | object { provider, component?, distribution?, owner?, package?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, token?, updaterCacheDirName?, user? } | object { provider, publishAutoUpdate?, publisherName?, requestHeaders?, updateProvider?, updaterCacheDirName?, <key>: {} } | object { account, product, provider, channel?, platform?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, channels?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, updaterCacheDirName? } | object { owner, provider, slug, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, token?, updaterCacheDirName?, username? } | string, ...] | null | string
   Details:
    * configuration.publish.provider should be "s3".
      -> The provider. Must be `s3`.
    * configuration.publish.provider should be "spaces".
      -> The provider. Must be `spaces`.
    * configuration.publish.provider should be "generic".
      -> The provider. Must be `generic`.
    * configuration.publish.provider should be "bintray".
      -> The provider. Must be `bintray`.
    * configuration.publish.provider should be "custom".
      -> The provider. Must be `custom`.
    * configuration.publish.provider should be "keygen".
      -> The provider. Must be `keygen`.
    * configuration.publish.provider should be "snapStore".
      -> The provider. Must be `snapStore`.
    * configuration.publish.provider should be "bitbucket".
      -> The provider. Must be `bitbucket`.
     How to fix:
     1. Open https://www.electron.build/configuration/configuration
     2. Search the option name on the page (or type in into Search to find across the docs).
       * Not found? The option was deprecated or not exists (check spelling).
       * Found? Check that the option in the appropriate place. e.g. "title" only in the "dmg", not in the root.

    at validate (D:\Entwicklung\Testing\electronVue\electron-vue3-flask\node_modules\@develar\schema-utils\dist\validate.js:86:11)
    at Object.validateConfig (D:\Entwicklung\Testing\electronVue\electron-vue3-flask\node_modules\app-builder-lib\src\util\config.ts:240:3)
    at Packager._build (D:\Entwicklung\Testing\electronVue\electron-vue3-flask\node_modules\app-builder-lib\src\packager.ts:342:5)
    at Packager.build (D:\Entwicklung\Testing\electronVue\electron-vue3-flask\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (D:\Entwicklung\Testing\electronVue\electron-vue3-flask\node_modules\builder-util\src\promise.ts:12:14) {
  errors: [
    {
      keyword: 'anyOf',
      dataPath: '.publish',
      schemaPath: '#/properties/publish/anyOf',
      params: {},
      message: 'should match some schema in anyOf',
      schema: [Array],
      parentSchema: [Object],
      data: [Object],
      children: [Array]
    }
  ],
  schema: {
    '$schema': 'http://json-schema.org/draft-07/schema#',
    additionalProperties: false,
    definitions: {
      AppImageOptions: [Object],
      AppXOptions: [Object],
      AsarOptions: [Object],
      BintrayOptions: [Object],
      BitbucketOptions: [Object],
      CustomNsisBinary: [Object],
      CustomPublishOptions: [Object],
      DebOptions: [Object],
      DmgContent: [Object],
      DmgOptions: [Object],
      DmgWindow: [Object],
      ElectronBrandingOptions: [Object],
      ElectronDownloadOptions: [Object],
      FileAssociation: [Object],
      FileSet: [Object],
      FlatpakOptions: [Object],
      GenericServerOptions: [Object],
      GithubOptions: [Object],
      KeygenOptions: [Object],
      LinuxConfiguration: [Object],
      LinuxTargetSpecificOptions: [Object],
      MacConfiguration: [Object],
      MasConfiguration: [Object],
      MetadataDirectories: [Object],
      MsiOptions: [Object],
      NsisOptions: [Object],
      NsisWebOptions: [Object],
      OutgoingHttpHeaders: [Object],
      PkgBackgroundOptions: [Object],
      PkgOptions: [Object],
      PlugDescriptor: [Object],
      PortableOptions: [Object],
      Protocol: [Object],
      ReleaseInfo: [Object],
      S3Options: [Object],
      SlotDescriptor: [Object],
      SnapOptions: [Object],
      SnapStoreOptions: [Object],
      SpacesOptions: [Object],
      SquirrelWindowsOptions: [Object],
      TargetConfiguration: [Object],
      WindowsConfiguration: [Object]
    },
    description: 'Configuration Options',
    properties: {
      afterAllArtifactBuild: [Object],
      afterPack: [Object],
      afterSign: [Object],
      apk: [Object],
      appId: [Object],
      appImage: [Object],
      appx: [Object],
      appxManifestCreated: [Object],
      artifactBuildCompleted: [Object],
      artifactBuildStarted: [Object],
      artifactName: [Object],
      asar: [Object],
      asarUnpack: [Object],
      beforeBuild: [Object],
      beforePack: [Object],
      buildDependenciesFromSource: [Object],
      buildVersion: [Object],
      compression: [Object],
      copyright: [Object],
      cscKeyPassword: [Object],
      cscLink: [Object],
      deb: [Object],
      defaultArch: [Object],
      detectUpdateChannel: [Object],
      directories: [Object],
      dmg: [Object],
      electronBranding: [Object],
      electronCompile: [Object],
      electronDist: [Object],
      electronDownload: [Object],
      electronUpdaterCompatibility: [Object],
      electronVersion: [Object],
      executableName: [Object],
      extends: [Object],
      extraFiles: [Object],
      extraMetadata: [Object],
      extraResources: [Object],
      fileAssociations: [Object],
      files: [Object],
      flatpak: [Object],
      forceCodeSigning: [Object],
      framework: [Object],
      freebsd: [Object],
      generateUpdatesFilesForAllChannels: [Object],
      icon: [Object],
      includePdb: [Object],
      includeSubNodeModules: [Object],
      launchUiVersion: [Object],
      linux: [Object],
      mac: [Object],
      mas: [Object],
      masDev: [Object],
      msi: [Object],
      msiProjectCreated: [Object],
      nodeGypRebuild: [Object],
      nodeVersion: [Object],
      npmArgs: [Object],
      npmRebuild: [Object],
      nsis: [Object],
      nsisWeb: [Object],
      onNodeModuleFile: [Object],
      p5p: [Object],
      pacman: [Object],
      pkg: [Object],
      portable: [Object],
      productName: [Object],
      protocols: [Object],
      publish: [Object],
      releaseInfo: [Object],
      remoteBuild: [Object],
      removePackageKeywords: [Object],
      removePackageScripts: [Object],
      rpm: [Object],
      snap: [Object],
      squirrelWindows: [Object],
      target: [Object],
      win: [Object],
      '$schema': [Object]
    },
    type: 'object'
  },
  headerName: 'electron-builder 22.14.13',
  baseDataPath: 'configuration',
  postFormatter: [Function: postFormatter]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Desktop (please complete the following information):**
 - OS: Windows 64bit

**Additional context**
[package-lock.zip](https://github.com/megasanjay/electron-vue3-flask/files/9146683/package-lock.zip)

**Comment by MarAlder** [comment]
I must have messed up something when first trying to install with `npm install`. I tried again with a clean copy doing everything with `yarn` and now its working. Sorry. Thanks again for this great template!!

**Comment by megasanjay** [comment]
Glad you were able to figure it out. Please do open another issue if you have more questions. Cheers 😄
