### ISSUE TITLE
Build with npm: ValidationError

### ISSUE THREAD

**Issue by MarAlder** [megasanjay/electron-vue3-flask#20]
**Bug description**
Building the example works fine with `yarn` following the readme:
```
yarn install
yarn python:build
yarn electron:build
```

However, doing the same with `npm` fails during `electron:build`:
```
npm install
npm run python:build
npm run electron:build
```
The error message:
```
Building app with electron-builder:
  • electron-builder  version=22.14.13 os=10.0.19044
ValidationError: Invalid configuration object. electron-builder 22.14.13 has been initialized using a configuration object that does not match the API schema.
 - configuration.publish should be one of these:
   object { provider, channel?, host?, owner?, private?, protocol?, publishAutoUpdate?, publisherName?, releaseType?, repo?, requestHeaders?, token?, updaterCacheDirName?, vPrefixedTagName? } | object { bucket, provider, acl?, channel?, encryption?, endpoint?, path?, publishAutoUpdate?, publisherName?, region?, requestHeaders?, storageClass?, updaterCacheDirName? } | object { name, provider, region, acl?, channel?, path?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, url, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName?, useMultipleRangeRequest? } | object { provider, component?, distribution?, owner?, package?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, token?, updaterCacheDirName?, user? } | object { provider, publishAutoUpdate?, publisherName?, requestHeaders?, updateProvider?, updaterCacheDirName?, <key>: {} } | object { account, product, provider, channel?, platform?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, channels?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, updaterCacheDirName? } | object { owner, provider, slug, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, token?, updaterCacheDirName?, username? } | [object { provider, channel?, host?, owner?, private?, protocol?, publishAutoUpdate?, publisherName?, releaseType?, repo?, requestHeaders?, token?, updaterCacheDirName?, vPrefixedTagName? } | object { bucket, provider, acl?, channel?, encryption?, endpoint?, path?, publishAutoUpdate?, publisherName?, region?, requestHeaders?, storageClass?, updaterCacheDirName? } | object { name, provider, region, acl?, channel?, path?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, url, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName?, useMultipleRangeRequest? } | object { provider, component?, distribution?, owner?, package?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, token?, updaterCacheDirName?, user? } | object { provider, publishAutoUpdate?, publisherName?, requestHeaders?, updateProvider?, updaterCacheDirName?, <key>: {} } | object { account, product, provider, channel?, platform?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, channels?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, updaterCacheDirName? } | object { owner, provider, slug, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, token?, updaterCacheDirName?, username? } | string, ...] | null | string
   Details:
    * configuration.publish.provider should be "s3".
      -> The provider. Must be `s3`.
    * configuration.publish.provider should be "spaces".
      -> The provider. Must be `spaces`.
    * configuration.publish.provider should be "generic".
      -> The provider. Must be `generic`.
    * configuration.publish.provider should be "bintray".
      -> The provider. Must be `bintray`.
    * configuration.publish.provider should be "custom".
      -> The provider. Must be `custom`.
    * configuration.publish.provider should be "keygen".
      -> The provider. Must be `keygen`.
    * configuration.publish.provider should be "snapStore".
      -> The provider. Must be `snapStore`.
    * configuration.publish.provider should be "bitbucket".
      -> The provider. Must be `bitbucket`.
     How to fix:
     1. Open https://www.electron.build/configuration/configuration
     2. Search the option name on the page (or type in into Search to find across the docs).
       * Not found? The option was deprecated or not exists (check spelling).
       * Found? Check that the option in the appropriate place. e.g. "title" only in the "dmg", not in the root.

    at validate (D:\Entwicklung\Testing\electronVue\electron-vue3-flask_npm\node_modules\@develar\schema-utils\dist\validate.js:86:11)
    at Object.validateConfig (D:\Entwicklung\Testing\electronVue\electron-vue3-flask_npm\node_modules\app-builder-lib\src\util\config.ts:240:3)
    at Packager._build (D:\Entwicklung\Testing\electronVue\electron-vue3-flask_npm\node_modules\app-builder-lib\src\packager.ts:342:5)
    at Packager.build (D:\Entwicklung\Testing\electronVue\electron-vue3-flask_npm\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (D:\Entwicklung\Testing\electronVue\electron-vue3-flask_npm\node_modules\builder-util\src\promise.ts:12:14) {
  errors: [
    {
      keyword: 'anyOf',
      dataPath: '.publish',
      schemaPath: '#/properties/publish/anyOf',
      params: {},
      message: 'should match some schema in anyOf',
      schema: [Array],
      parentSchema: [Object],
      data: [Object],
      children: [Array]
    }
  ],
  schema: {
    '$schema': 'http://json-schema.org/draft-07/schema#',
    additionalProperties: false,
    definitions: {
      AppImageOptions: [Object],
      AppXOptions: [Object],
      AsarOptions: [Object],
...
```

[Complete log: log.txt](https://github.com/megasanjay/electron-vue3-flask/files/9747350/log.txt)

The use of "yarn" is fine with me, but I would like to understand the error better, as I fear the problem is more fundamental. Any help is appreciated. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/43143741/194905192-1429ded4-eb8d-4835-a8a0-a7447f4e06a4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - npm version: 8.19.2
 - yarn version: 1.22.19

**Comment by MarAlder** [comment]
Solved after updating packages.
